/*
 系统相关表
 */
-- 用户登录表
CREATE TABLE sys_user_login (
    `id` INT AUTO_INCREMENT COMMENT '自增ID',
    `user_id` VARCHAR(10) NOT NULL COMMENT '用户ID',
    `nickname` VARCHAR(32) NULL COMMENT '用户昵称',
    `remote_addr` VARCHAR(64) NOT NULL COMMENT '登录IP',
    `user_agent` VARCHAR(256) NOT NULL COMMENT '用户代理',
    `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '登录状态,0:禁用,1:启用',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT '用户登录表-用于登录';

-- 应用配置表
CREATE TABLE sys_config (
    `id` INT AUTO_INCREMENT COMMENT '配置ID',
    `parent_id` INT(11) DEFAULT NULL COMMENT '父节点ID',
    `name` VARCHAR(32) NOT NULL COMMENT '配置名称',
    `key` VARCHAR(32) NOT NULL UNIQUE COMMENT '配置项(英文)',
    `value` TEXT COMMENT '配置参数值',
    `sort` INT(11) NOT NULL DEFAULT 0 COMMENT '排序',
    `note` VARCHAR(32) DEFAULT NULL COMMENT '配置描述',
    `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用,0: 禁用,1: 启用',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT '应用配置表';

-- ICON图标表
CREATE TABLE sys_icon (
    `id` INT AUTO_INCREMENT COMMENT '配置ID',
    `name` VARCHAR(32) NOT NULL COMMENT '配置名称',
    `value` VARCHAR(32) NOT NULL COMMENT '配置值',
    `category` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '图标类型,1:element,2:custom',
    `note` VARCHAR(32) DEFAULT NULL COMMENT '配置描述',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT 'ICON图标表';