import { createApp } from 'vue';
import { createPinia } from 'pinia';
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate';
import ElementPlus from 'element-plus';
import VXETable from 'vxe-table';
import App from './App.vue';
import router from './router';
import './theme/index.scss';
import 'uno.css';
import { setupI18n } from '@/lang';
import '@/styles/index.scss';
import 'virtual:svg-icons-register';
import svgIcon from '@/icons/SvgIcon.vue';
import directive from '@/directives';
import './permission';
import 'element-plus/dist/index.css';
import 'vxe-table/lib/style.css';
import 'highlight.js/styles/atom-one-dark.css';
import 'highlight.js/lib/common';
import hljsVuePlugin from '@highlightjs/vue-plugin';
import * as errorLog from './utils/errorHandler';
const app = createApp(App);
app.use(router);
const pinia = createPinia();
pinia.use(piniaPluginPersistedstate);
app.use(pinia);
app.use(setupI18n);
app.component('SvgIcon', svgIcon);
directive(app);
app.use(ElementPlus, { size: 'small', zIndex: 3000 });
app.use(VXETable);
app.use(hljsVuePlugin);
app.config.warnHandler = errorLog.warnHandler;
app.config.errorHandler = errorLog.errorHandler;
window.onerror = errorLog.onerrorHandler;
app.mount('#app');
