export const settings = {
    title: '后台管理系统',
    fixedHeader: true,
    sidebarLogo: true,
    showNavbarTitle: false,
    ShowDropDown: true,
    showHamburger: true,
    showLeftMenu: true,
    showTagsView: true,
    tagsViewNum: 6,
    showTopNavbar: true,
    showFooter: true,
    mainNeedAnimation: false,
    isNeedNprogress: true,
    isNeedLogin: true,
    permissionMode: 'rbac',
    openProdMock: false,
    errorLog: ['prod'],
    delWindowHeight: '210px',
    tmpToken: 'tmp_token',
    viteBasePath: './',
    defaultLanguage: 'en',
    defaultTheme: 'base-theme',
    defaultSize: 'default',
    plateFormId: 2,
    defaultPassword: '888888',
};
export default settings;
