// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonPermission: typeof import('./../components/ButtonPermission.vue')['default']
    ConvenienButtons: typeof import('./../components/ConvenienButtons/index.vue')['default']
    ConvenienTools: typeof import('./../components/ConvenienTools/index.vue')['default']
    copy: typeof import('./../components/ConvenienTools copy/index.vue')['default']
    ElSvgIcon: typeof import('./../components/ElSvgIcon.vue')['default']
    Pagination: typeof import('./../components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenFull: typeof import('./../components/ScreenFull.vue')['default']
    SvgIcon: typeof import('./../icons/SvgIcon.vue')['default']
    TestUnit: typeof import('./../components/TestUnit.vue')['default']
  }
}
