// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonPermission: typeof import('./../components/ButtonPermission.vue')['default']
    ConvenienButtons: typeof import('./../components/ConvenienButtons/index.vue')['default']
    ConvenienTools: typeof import('./../components/ConvenienTools/index.vue')['default']
    copy: typeof import('./../components/IconMenu copy/index.vue')['default']
    CustomIcon: typeof import('./../components/IconMenu/CustomIcon.vue')['default']
    ElementIcon: typeof import('./../components/IconMenu/ElementIcon.vue')['default']
    ElSvgIcon: typeof import('./../components/ElSvgIcon.vue')['default']
    Icon: typeof import('./../components/Icon.vue')['default']
    IconMenu: typeof import('./../components/IconMenu/index.vue')['default']
    IconMenu2: typeof import('./../components/IconMenu2/index.vue')['default']
    Pagination: typeof import('./../components/Pagination.vue')['default']
    PhotoWall: typeof import('./../components/Upload/PhotoWall.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../icons/SvgIcon.vue')['default']
    TestUnit: typeof import('./../components/TestUnit.vue')['default']
    UploadAvatar: typeof import('./../components/Upload/UploadAvatar.vue')['default']
    UploadLogo: typeof import('./../components/Upload/UploadLogo.vue')['default']
  }
}
